AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'

Metrics/LineLength:
  Max: 125

MethodLength:
  CountComments: false
  Max: 30

Style/BracesAroundHashParameters:
  Exclude:
    - spec/*.rb

BlockLength:
  Exclude:
    - spec/*.rb
