production:
  username: postgres
  host: db
  adapter: postgresql
  database: lti2_reference_tool_production
  encoding: unicode
  pool: 5

development:
  adapter: sqlite3
  database: db/tp-development.sqlite3

test:
  adapter: sqlite3
  database: db/tp-test.sqlite3
